cabal-version:      3.0
name:               chap2
version:            0.1.0.0
homepage:           https://github.com/cutsea110/coreml.git
license:            BSD-3-Clause
license-file:       LICENSE
author:             cutsea110
maintainer:         cutsea110@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md
common warnings
    ghc-options: -Wall
library
    exposed-modules:  TM
                      Eval
                      Compiler
    build-depends:    base, containers
    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall
executable chap2
    import:           warnings
    main-is:          Main.hs
    build-depends:    base, chap2
    hs-source-dirs:   app
    default-language: Haskell2010
    ghc-options:      -Wall
