cabal-version:      3.0
name:               compiler
version:            0.1.0.0
build-type:         Simple

common warnings
    ghc-options: -Wall

library
    exposed-modules:  Token
                      Lexer
                      Parser
    build-depends:    base, containers, directory
    hs-source-dirs:   lex
    default-language: GHC2024
    ghc-options:      -Wall
executable coremlc
    import:           warnings
    main-is:          Main.hs
    other-modules:    Top
    build-depends:    base, compiler
    hs-source-dirs:   main
    default-language: GHC2024

test-suite doctest
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Doctest.hs
    build-depends:    base ^>=4.22.0.0, doctest, directory
    hs-source-dirs:   test
    default-language: GHC2024
